package app.dora.localai.engine

import app.dora.localai.domain.ChatMessage
import app.dora.localai.domain.LocalModel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

interface TextInferenceEngine {
    val displayName: String
    val isProductionReady: Boolean
    fun streamReply(model: LocalModel, history: List<ChatMessage>): Flow<String>
}

interface ImageInferenceEngine {
    val displayName: String
    val isProductionReady: Boolean
    suspend fun generate(model: LocalModel, prompt: String): Result<String>
}

/**
 * A deterministic offline engine used until the native llama.cpp bridge is added.
 * It intentionally labels itself as a demo so the UI never implies that a cloud
 * service or a bundled model is running behind the scenes.
 */
class DoraDemoTextEngine : TextInferenceEngine {
    override val displayName: String = "Dora offline demo engine"
    override val isProductionReady: Boolean = false

    override fun streamReply(model: LocalModel, history: List<ChatMessage>): Flow<String> = flow {
        val prompt = history.lastOrNull { it.role.name == "USER" }?.text.orEmpty()
        val response = if (prompt.isBlank()) {
            "Dora is ready. Add a local model to connect a production runtime."
        } else {
            "I received: \"$prompt\"\n\nThis response was generated by Dora’s offline demo engine. The production llama.cpp/GGUF bridge will replace this adapter without changing the chat UI."
        }
        response.split(" ").forEachIndexed { index, token ->
            emit(if (index == 0) token else " $token")
            delay(18)
        }
    }
}

class DoraDemoImageEngine : ImageInferenceEngine {
    override val displayName: String = "Dora image runtime seam"
    override val isProductionReady: Boolean = false

    override suspend fun generate(model: LocalModel, prompt: String): Result<String> {
        delay(600)
        return Result.failure(
            IllegalStateException("No image runtime is bundled yet. Install a validated local image backend to enable generation.")
        )
    }
}
